version: '3.3'

services:

  employee-management-api:
    image: employee-management-api:1.0.0
    environment:
      - MONGO_URI=mongo
      - MONGO_PORT=27017
      - MONGO_DB=employee
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always