version: '3.3'

services:

  employee-management-api:
    image: employee-management-api:1.0.0
    environment:
      - MONGO_URL=mongo
      - MONGO_PORT=27017
      - MONGO_DB=employee
      - BASE_URL=http://localhost:5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  nginx-employee-management-api:
    image: nginx-employee-management-api:1.0.0
    depends_on:
      - employee-management-api
    ports:
      - "80:80"

  mongo:
    image: mongo
    restart: always